version: '2'

services:
  web:
    image: openlab/ongoingness-webapp
    build: .
    ports:
      - '3333:3333'

  api:
    image: openlab/ongoingness-api
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      SECRET: ${APP_SECRET}
      LOCAL: ${LOCAL}
      MONGO_URI: ${MONGO_URI}
      MONGO_URI_LOCAL: ${MONGO_URI_LOCAL}
      MONGO_USER: ${MONGODB_USER}
      MONGO_PASS: ${MONGODB_PASS}
      MONGO_DATABASE: ${MONGODB_DATABASE}
      PRODUCTION: ${APP_PRODUCTION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
      TEST: ${TEST}
      PORT: ${APP_PORT}
      DB_TYPE: ${DB_TYPE}

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - 'data:/data/db'

volumes:
  data:
